# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4d5697ac1d904576864185becf6956202ff14c5973bbc3f975feb2b886e4772023abc8a5a0d733acdbd050bcf586d4273bda298b27c8b24f56b2d863ebdd73d

test:
  secret_key_base: 5c1e6129e5f517c9ebe714f2cf48d8179579472db7375fafcf8c229f5606e9284f799c02a13f61c2ac8e95861312adc46805262bcd01476a002dc8f538be7ff6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
